### ISSUE TITLE
Add a SW07 example to the draft catalog

### ISSUE THREAD

**Issue by scottveirs** [orcasound/signals-srkw#11]
```[tasklist]
### Tasks
- [ ] Find an example of an SW07 in Orcasound open data
- [ ] Extract a sample in wav format via Audacity export
- [ ] Use Emily script to generate PNG spectrogram from .wav file
- [ ] Add .wav file to the repo in `signals/processed/whistles/`
- [ ] Scott: pull down .wav file and convert to SW07.mp3 and SW07.ogg format
- [ ] Upload .mp3, .ogg, and PNG files to `https://www.orcasound.net/data/product/biophony/SRKW/whistle-catalog/` via FTP
```
