### ISSUE TITLE
Automate the creation of a whistle catalog

### ISSUE THREAD

**Issue by scottveirs** [orcasound/signals-srkw#9]
Instead of manually building the whistle catalog, come up with a scheme to automatically built it.

```[tasklist]
### Tasks
- [ ] test Emily's code in your local Python environment +/- IDE (not just a notebook)
- [ ] get Emily's for loop working with our whistle signal directory structure
- [ ] Scott: move Emily's humpback audio to a new repo named `signals-humpback` and release first version
- [ ] reorganize code in the `signal-catalogue` repo
- [ ] Rewrite the `signal-catalogue` repo README to explain how to deploy the newly-generated catalog (Wordpress, orcasound.net/data, Github page...)
```
